version: '3.8'

services:
  app:
    build: .
    container_name: project-api-graphql
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge